name: Azure Pages CI/CD

on:
  push:
    branches:
    - workbox-step7
  pull_request:
    types: [opened, synchronize, reopened, closed]
    branches:
    - workbox-step7

jobs:
  build_and_deploy_job:
    if: github.event_name == 'push' || (github.event_name == 'pull_request' && github.event.action != 'closed')
    runs-on: ubuntu-latest
    name: Build and Deploy Job
    steps:
    - uses: actions/checkout@v1
    - name: Build And Deploy
      id: builddeploy
      uses: joslinmicrosoft/staticsitesactionoryx@canary3
      with:
        azure_pages_api_token: ${{ secrets.AZURE_PAGES_API_TOKEN_WITTY_DUNE_0840A0B04 }}
        repo_token: ${{ secrets.GITHUB_TOKEN }} # Used for Github integrations (i.e. PR comments)
        action: 'upload'
        ###### Repository/Build Configurations - These values can be configured to match you app requirements. ######
        app_location: '/dist' # App source code path
        api_location: 'api' # Api source code path - optional
        app_artifact_location: '' # Built app content directory - optional
        ###### End of Repository/Build Configurations ######

  close_pull_request_job:
    if: github.event_name == 'pull_request' && github.event.action == 'closed'
    runs-on: ubuntu-latest
    name: Close Pull Request Job
    steps:
    - name: Close Pull Request
      id: closepullrequest
      uses: joslinmicrosoft/staticsitesaction@canary2
      with:
        azure_pages_api_token: ${{ secrets.AZURE_PAGES_API_TOKEN_WITTY_DUNE_0840A0B04 }}
        action: 'close'
